image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache: &global_cache
  paths:
    - node_modules/
    - public/
    

before_script:  
  - apt-get update
  - apt -y install python2

stages:
  - install
  - pages
  - deploy

before_script:  
  - apt-get update
  - apt -y install python2

install:
  stage: install
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - npm install --no-progress  --legacy-peer-deps

pages:
  stage: pages
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - public
  only:
    - main

deploy:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - yarn build-gitlab
    - cd dist
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - main