image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:  
  - apt-get -y install software-properties-common
  - add-apt-repository ppa:deadsnakes/ppa
  - apt-get update
  - apt-get -y install python3.8

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install --no-progress  --legacy-peer-deps
    - yarn build-gitlab
    - cd dist
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish.