image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache: &global_cache
  paths:
    - node_modules/
    - public/
    

before_script:  
  - apt-get update
  - apt -y install python-is-python3

stages:
  - install-main
  - install-pages
  - pages
  - deploy

before_script:  
  - apt-get update
  - apt -y install python-is-python3

install-main:
  stage: install-main
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - npm install --no-progress  --legacy-peer-deps --omit=dev --ignore-scripts
  only:
    - main

install-pages:
  stage: install-pages
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - npm install --no-progress  --legacy-peer-deps --ignore-scripts
  only:
    - gitlab-pages

pages:
  stage: pages
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - public
  only:
    - gitlab-pages

deploy:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
  script:
    - yarn build-gitlab
    - cd dist
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - main