#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node hooks/main_requirements.js
mainBranch=`git rev-parse --abbrev-ref HEAD`
if [ "$mainBranch" = "husky-test-yarn-build-fix" ]; then
    git checkout gitlab-pages
    git merge husky-test-yarn-build-fix
    git push origin gitlab-pages
    git checkout husky-test-yarn-build-fix
fi