#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node hooks/main_requirements.js
mainBranch=`git rev-parse --abbrev-ref HEAD`
if [ "$mainBranch" = "test-gitattributes-gitlab-pages" ]; then
    git checkout gitlab-pages
    git merge test-gitattributes-gitlab-pages
    git push origin gitlab-pages
    git checkout test-gitattributes-gitlab-pages
fi