name: Check package json modification

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: 
        actions/checkout@v4 
      with:
        fetch-depth: 2  # This is important to fetch the previous commit as well



    - name: Check version increase in package.json
      run: |
        # Get the version from the current commit
        CURRENT_VERSION=$(jq -r .version package.json)

        # Checkout the previous commit
        git fetch origin main:main
        git checkout main

        # Get the version from the previous commit
        MAIN_VERSION=$(jq -r .version package.json)

        # Compare the versions
        echo "New version ($CURRENT_VERSION). Main version ($MAIN_VERSION)."
        if [[ "$CURRENT_VERSION" == "$MAIN_VERSION" ]]; then
          echo "Error: Version in package.json has not been increased!"
          exit 1
        else
          echo "Success: Version has been increased successfully!"
        fi