name: 'Deploy Pages'

on:
  push:
    branches:
      - pages

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@hermosillo-i3'

      - name: Install dependecies 
        run: npm install --no-progress  --legacy-peer-deps --ignore-scripts

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: pages # The branch the action should deploy to.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
