name: Create pull request to merge hotfix or release into develop

on:
  pull_request:
    branches: [main]
    types: [closed] 
  
jobs:
  new-pull-request-to-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Create pull request to merge hotfix or release into develop
      run: gh pr create -B develop -H ${{ github.event.pull_request.head.ref }} --title 'Merge ${{ github.event.pull_request.head.ref }} into develop' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
